### PR TITLE
IT-CUUO

### LINKED ISSUE #460: PROPOSAL: Italian organisational unit code for public services and agencies
## Proposal

**What open data standard are you working with? (e.g. 'OCDS', '360Giving', 'BODS' etc.)**

OCDS. Adding this list to org-id would align it with ISO 6523 (See open-contracting/standard#987). ICD 0201

**The name of the list (or the organization that manages the list)**

Codice Univoco Unità Organizzativa iPA (managed by Agenzia per l’Italia digitale (AGID))

**A suggested code for the list (optional)**

IT-CUUO

**A short description of the list**

"Used to identify uniquely all organizational units of public bodies, authorities and public services in Italy. Issuing agency: Agenzia per l’Italia digitale in Italy." (from https://docs.peppol.eu/poacc/billing/3.0/codelist/ICD/)

**The country or countries that the list covers**

Italy

**The legal form or organizations that the list covers**

**Any specific sectors that the list covers**

Public sector

**A URL for information on the list, and a URL for looking up identifiers (if available)**

https://www.indicepa.gov.it/ipa-portale/consultazione/domicilio-digitale/ricerca-unita-organizzativa/scheda-unita-organizzativa/2GLM8E

**Any information on available open data copies of this list**

**One or more examples of identifier from this list, and how you found them**
2GLM8E (need to work out whether this needs to be paired with the codice IPA to uniquely identify the body).

### PR DESCRIPTION
**Pull request by duncandewhurst**
Closes #460 

TO-DO:

- [x] Update list description with an explanation of how organisations end up on this list

### CODE REVIEW

**Review by kd-ods — APPROVED** [review]
Looks good.

**Review by kd-ods — CHANGES_REQUESTED** [review]
I spoke too soon. I just noticed that that filename should be it-cuuo.json

I think that's why we can't preview the list on datatig.

**Comment by duncandewhurst** [comment]
Whoops. Good spot!

**Review by kd-ods — APPROVED** [review]
It's good to go.

**Pull request merged**
