### PR TITLE
Flesh out Wikidata record

### PR DESCRIPTION
**Pull request by wetneb**
This adds some more info about Wikidata, which holds about 1.2M records about organizations.

### CODE REVIEW

**Comment by wetneb** [comment]
@BobHarper1 hi! have you had any time to have a look at this?

**Comment by BobHarper1** [comment]
Hi @wetneb sorry for this dropping off my radar! I'll progress it through PR #197 (same changes, just as a branch off the main project) to follow the normal procedure for adding lists (that 7-day wait).

**Comment by wetneb** [comment]
no problem, it's my fault for not following the normal procedure!

**Comment by BobHarper1** [comment]
Hey, not at all! I'm very grateful for your direct contribution :)

**Pull request closed without merging**
