### PR TITLE
New  registry entry for 'NHS Digital - Organisation Data Service' (GB-NHS)

### PR DESCRIPTION
**Pull request by BobHarper1**
A new list has been proposed with the code GB-NHS

**List title:** NHS Digital - Organisation Data Service

addition of GB-NHS #184 

~Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-NHS](http://org-id.guide/_preview_branch/GB-NHS)  (visiting [http://org-id.guide/list/GB-NHS](http://org-id.guide/list/GB-NHS) when the preview is active~ or check the files changed options above.

Unless objections are raised, this update will be merged after 7 days.

### CODE REVIEW

**Comment by KDuerden** [comment]
The NHS digital service now has online search facility, so it's much easier to find info
https://odsportal.hscic.gov.uk/Organisation/Search
Scope to update the 'Search' section of the http://org-id.guide/list/GB-NHS entry.

**Comment by siwhitehouse** [comment]
Thanks @KDuerden - I'll add the online search facility to the 'Search' section, as suggested. I can only see the ability to search and view organisation information as presented on the search site. I don't see any way of downloading data for individual organisations nor for downloading the whole dataset. 

Is that your understanding too, or am I missing anything here.

**Comment by KDuerden** [comment]
It seems you can still get bulk file downloads here: https://digital.nhs.uk/services/organisation-data-service/data-downloads, but segmented into org types. I can't see a function to download individual entries though.

**Comment by siwhitehouse** [comment]
Thank you - I have raised a Pull Request at #330 to update the entry for GB-NHS.

**Pull request merged**
