### PR TITLE
New  registry entry for 'Tax Identification Number (Poland)' (PL-NIP)

### PR DESCRIPTION
**Pull request by orgidguide**
A new list has been proposed with the code PL-NIP

**List title:** Tax Identification Number (Poland)

 Preview the platform with this list at [http://org-id.guide/_preview_branch/PL-NIP](http://org-id.guide/_preview_branch/PL-NIP)  (visiting [http://org-id.guide/list/PL-NIP](http://org-id.guide/list/PL-NIP) when the preview is active or check the files changed options above.

Unless objections are raised, this update will be merged after 7 days.

### CODE REVIEW

**Comment by timgdavies** [comment]
Based on #18 I've created this pull request. 

I made minor changes to the details in #18 to:

* List this as a secondary identifier (http://docs.org-id.guide/en/latest/metadata/#list-type) on the understanding that, as a tax identifier, this is less stable than the registration number in #23 PL-KRS 

* To describe how to locate an identifier for an organisation by their address;

**Comment by timgdavies** [comment]
As the overall request in #18 has been open already for five days, this will be merged by Wednesday 12th July unless other issues raised.

**Comment by KrzysztofMadejski** [comment]
@timgdavies NIP is as stable as KRS. I've checked with our CFO and all the Polish identifiers: KRS, REGON and NIP - they don't change. So I believe all should be primary.

**Comment by KrzysztofMadejski** [comment]
If I had to choose one though I'd choose KRS - getting it makes you an official legal entity and allows to make legal transactions.

**Comment by timgdavies** [comment]
Thanks - that was my reading - that the KRS is the identifier most tightly tied to being a legal entity. 

If we make all of these primary, then it makes it trickier for our current ranking algorithm to suggest KRS above the others I believe - but will investigate before final merge.

**Pull request merged**
