### PR TITLE
New  registry entry for 'National Identification Number of Companies and Associations (Senegal)' (SN-NINEA)

### PR DESCRIPTION
**Pull request by BobHarper1**
A new list has been proposed with the code SN-NINEA

**List title:** National Identification Number of Companies and Associations (Senegal)

Adding SN-NINEA list (Senegal)

 Preview the platform with this list at [http://org-id.guide/_preview_branch/SN-NINEA](http://org-id.guide/_preview_branch/SN-NINEA)  (visiting [http://org-id.guide/list/SN-NINEA](http://org-id.guide/list/SN-NINEA) when the preview is active or check the files changed options above.

Unless objections are raised, this update will be merged after 7 days.

### CODE REVIEW

**Comment by BobHarper1** [comment]
Original request #36

**Comment by timgdavies** [comment]
Reviewed, and happy to see this merged after the waiting period.

**Comment by ScatteredInk** [comment]
Just to flag that there is a search database for Senegal at Le Bureau d’Appui à la Création d’entreprise [(BCE)](http://creationdentreprise.sn/en/finding-business). I don't think that this is comprehensive, or at least there are entities that I am sure exist/have existed that I can't find. I'm unsure if this is a coverage or a search issue.

There are also legal entities in this database that have a Régistre de commerce identifier without a NINEA. [Example](http://creationdentreprise.sn/en/node/24668).

This is not an objection to this listing, but it may be worth adjusting the guidance.

**Comment by timgdavies** [comment]
Thanks @ScatteredInk - I'll review and make changes to the guidance before this gets merged.

**Comment by BobHarper1** [comment]
Thanks for finding this @ScatteredInk - Hope you don't mind @timgdavies but I've just committed some changes to the PR which you can review.

Re completeness, I think the best thing we can do is include it and assume it is as complete as these things can be. 

I think the Régistre de Commerce number relates to the registration filings with the government department. I'm not sure if this is as persistent as the NINEA should be.  The example Jack links of one having an RC but no NINEA is listed as an "anonymous company" and has fewer of the other details as well. Not sure what that means but might be a reason there is no NINEA (might be interesting for BODS, eh?)

**Comment by ScatteredInk** [comment]
Thanks @BobHarper1. In case you run into this again, 'Anonymous company' is a bit of a misnomer from an auto-translated website. It's from [Société Anonyme or S.A.](http://www.investopedia.com/terms/s/socit-anonyme.asp), which are not necessarily anonymous legal entities. There are similar terms in Spanish, Portuguese and probably more - so may be good to be aware of that for orgID.

**Comment by BobHarper1** [comment]
Thanks @ScatteredInk. 

Think we're happy here. Merged.

**Pull request merged**
