### PR TITLE
New  registry entry for 'REGON - Statistical number of an economy entity' (PL-REGON)

### PR DESCRIPTION
**Pull request by orgidguide**
A new list has been proposed with the code PL-REGON

**List title:** REGON - Statistical number of an economy entity

 Preview the platform with this list at [http://org-id.guide/_preview_branch/PL-REGON](http://org-id.guide/_preview_branch/PL-REGON)  (visiting [http://org-id.guide/list/PL-REGON](http://org-id.guide/list/PL-REGON) when the preview is active or check the files changed options above.

Unless objections are raised, this update will be merged after 7 days.

### CODE REVIEW

**Comment by timgdavies** [comment]
This pull request picks up on #19 and makes a minor edit to set PL-REGON as a secondary identifier. 

As #19 has already been open for five days, this will be merged by Weds 12th July unless any issues raised.

**Comment by KrzysztofMadejski** [comment]
As REGON is obligatory, not an opt-in, so I believe it should be primary identifier, at least that's how I've understood the docs.

**Comment by timgdavies** [comment]
Thanks @KrzysztofMadejski 

If you had both a KRS and REGON for an organisation, which would have the best chance of remaining a long-term stable identifier that always applies to the same legal entity, and which would be able to tell you whether the entity is still active or not? 

My understanding from the line "The identifier provides no implicit or explicit information on the features of an entity." was that whilst the KRS registers the company and is the primary legal identifier, the REGON is secondary in that it is used by the statistical authority rather than the company register, to identify the organisation for statistical rather than registration purposes?

**Comment by KrzysztofMadejski** [comment]
`which would have the best chance of remaining a long-term stable identifier that always applies to the same legal entity?`: both (also NIP)
`which would be able to tell you whether the entity is still active or not`: most of the search engines from official databases allows to search using any of the three IDs

`the REGON is secondary in that it is used by the statistical authority rather than the company register` - I agree.

**Pull request merged**
